gui:
  mouseEvents: true
  showDivergenceFromBaseBranch: arrowAndNumber
  mainPanelSplitMode: vertical
  sidePanelWidth: 0.2
refresher:
  refreshInterval: 5
notARepository: skip
git:
  diffContextSize: 5
  log:
    showWholeGraph: true
  pagers:
    - colorArg: always
      pager: delta --paging=never --side-by-side
